create database if not exists market_cubos

CREATE TABLE IF NOT EXISTS public.usuarios (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar NOT NULL,
	nome_loja varchar NOT NULL,
	email varchar NOT NULL,
	senha varchar NOT NULL,
	CONSTRAINT usuarios_un UNIQUE (nome_loja,email),
	CONSTRAINT usuarios_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.newtable (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	usuario_id int NOT NULL,
	nome varchar NOT NULL,
	estoque int NOT NULL,
	categoria varchar NULL,
	preco int NOT NULL,
	descricao text NULL,
	imagem text NULL,
	CONSTRAINT newtable_pk PRIMARY KEY (id),
	CONSTRAINT newtable_fk FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE
);
